In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [56]:
import pandas as pd

# Load your data
data = pd.read_csv('wine_production.csv')
data.fillna('0', inplace=True)
data.set_index('Year', inplace=True)
data = data.loc[1900:]
for column in data.columns:
    data[column] = pd.to_numeric(data[column].str.replace(',', ''), errors='coerce').fillna(0).astype(int)
data = data.T
data = data.sort_index()

country_info = pd.read_csv('country_info.csv')
country_info.set_index('Country Name', inplace=True)

combined_data = country_info.merge(data, left_index=True, right_index=True)

In [57]:
missing_indices = data.index.difference(country_info.index)
missing_indices

Index(['Hong Kong', 'Other', 'Other AME', 'Other Asia Pacific', 'Other ECA',
       'Other LAC', 'Other WEM', 'Taiwan', 'World'],
      dtype='object')

In [59]:
combined_data.head()

,Region,Image URL,1900,1901,1902,1903,1904,1905,1906,1907,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
Algeria,Africa,https://public.flourish.studio/country-flags/s...,544418,556303,366611,597368,791558,774035,690572,860123,...,52000,69816,58840,47500,48000,49200,49800,52000,0,0
Argentina,Americas,https://public.flourish.studio/country-flags/s...,115100,184400,136000,189200,174100,183800,242600,262100,...,1504600,1467764,1213547,1625077,1547300,1166025,1498400,1517900,1335800,940000
Australia,Oceania,https://public.flourish.studio/country-flags/s...,14919,25493,26440,23576,28459,26603,25412,27008,...,961972,1244778,1179191,1151656,1125986,1236145,1245602,1186343,1191193,1310000
Austria,Europe,https://public.flourish.studio/country-flags/s...,164281,172533,103232,95161,120804,198263,106573,41240,...,262803,299372,235188,173745,281476,215475,239195,199869,230000,200000
Belgium,Europe,https://public.flourish.studio/country-flags/s...,0,17182,14302,11422,8542,5663,2783,4124,...,14197,15967,16479,14025,17899,11368,12989,15394,16000,16000

In [60]:
combined_data.to_csv('wine_production_cleaned.csv')